# Generated by Django 3.2.9 on 2021-12-03 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kviz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('ime', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=1000)),
                ('slika', models.CharField(max_length=200)),
                ('longitude', models.FloatField(max_length=10)),
                ('latitude', models.FloatField(max_length=10)),
                ('type', models.CharField(max_length=200)),
                ('vprasanja', models.CharField(max_length=1000)),
                ('pravilni_odgovori', models.CharField(max_length=1000)),
                ('kviz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.kviz')),
            ],
        ),
        migrations.CreateModel(
            name='Odgovor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('odgovori', models.CharField(max_length=1000)),
                ('vprasanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.question')),
            ],
        ),
    ]
