# Generated by Django 3.2.9 on 2021-12-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kviz',
            name='name',
            field=models.CharField(default='Kviz 1', max_length=30),
        ),
    ]
