# Generated by Django 3.2.9 on 2021-12-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20211204_1356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dbKviz',
            new_name='dbQuiz',
        ),
    ]
