# Generated by Django 3.2.9 on 2021-12-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20211204_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='IzberiOdgovorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=1000)),
                ('slika', models.CharField(max_length=200)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('vprasanje', models.CharField(max_length=100)),
                ('odgovor1', models.CharField(default='nan', max_length=100)),
                ('odgovor2', models.CharField(default='nan', max_length=100)),
                ('odgovor3', models.CharField(default='nan', max_length=100)),
                ('odgovor4', models.CharField(default='nan', max_length=100)),
                ('odgovor5', models.CharField(default='nan', max_length=100)),
                ('pravilni_odgovor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OpisnoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=1000)),
                ('slika', models.CharField(max_length=200)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('vprasanje', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PravilnoNepravilnoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=1000)),
                ('slika', models.CharField(max_length=200)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('vprasanje', models.CharField(max_length=1000)),
                ('pravilni_odgovor', models.CharField(default='nan', max_length=1000)),
            ],
        ),
    ]
