# Generated by Django 3.2.9 on 2021-12-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_izberiodgovormodel_opisnomodel_pravilnonepravilnomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pravilnonepravilnomodel',
            name='vprasanje',
            field=models.CharField(default='nan', max_length=1000),
        ),
    ]
