# Generated by Django 3.2.9 on 2021-12-06 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_pravilnonepravilnomodel_vprasanje'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dbQuestion',
        ),
        migrations.AddField(
            model_name='izberiodgovormodel',
            name='kviz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.dbquiz'),
        ),
        migrations.AddField(
            model_name='opisnomodel',
            name='kviz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.dbquiz'),
        ),
        migrations.AddField(
            model_name='pravilnonepravilnomodel',
            name='kviz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.dbquiz'),
        ),
    ]
