# Generated by Django 3.2.9 on 2021-12-09 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20211206_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdgovorIzberiOdgovorModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('odgovori', models.CharField(max_length=1000)),
                ('vprasanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.izberiodgovormodel')),
            ],
        ),
        migrations.CreateModel(
            name='OdgovorOpisnoModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('odgovori', models.CharField(max_length=1000)),
                ('vprasanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.opisnomodel')),
            ],
        ),
        migrations.CreateModel(
            name='OdgovorPravilnoNepravilnoModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('odgovori', models.CharField(max_length=1000)),
                ('vprasanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.pravilnonepravilnomodel')),
            ],
        ),
        migrations.DeleteModel(
            name='dbAnswer',
        ),
    ]
