# Generated by Django 3.2.9 on 2021-12-17 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20211209_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbquiz',
            name='pictureUrl',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dbquiz',
            name='name',
            field=models.CharField(default='Kviz 1', max_length=200),
        ),
        migrations.AlterField(
            model_name='dbquiz',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='DatotekaPravilnoNepravilnoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datoteka', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('vprasanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.pravilnonepravilnomodel')),
            ],
        ),
        migrations.CreateModel(
            name='DatotekaOpisnoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datoteka', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('vprasanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.opisnomodel')),
            ],
        ),
        migrations.CreateModel(
            name='DatotekaIzberiOdgovorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datoteka', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('vprasanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.izberiodgovormodel')),
            ],
        ),
    ]
