# Generated by Django 3.2.9 on 2021-12-18 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20211217_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='izberiodgovormodel',
            name='slika',
        ),
        migrations.RemoveField(
            model_name='opisnomodel',
            name='slika',
        ),
        migrations.RemoveField(
            model_name='pravilnonepravilnomodel',
            name='slika',
        ),
    ]
