# Generated by Django 3.2.9 on 2021-12-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20211226_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbquiz',
            name='pictureUrl',
        ),
        migrations.AddField(
            model_name='dbquiz',
            name='datoteka',
            field=models.FileField(default='romans.jpg', upload_to='media/'),
            preserve_default=False,
        ),
    ]
