# Generated by Django 3.2.9 on 2021-12-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_auto_20211227_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbquiz',
            name='password',
            field=models.CharField(default='hec', max_length=200),
        ),
    ]
