# Generated by Django 3.2.9 on 2022-01-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_dbquiz_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='izberiodgovormodel',
            name='pozicijaOznake',
            field=models.CharField(default='err', max_length=1000),
        ),
        migrations.AddField(
            model_name='opisnomodel',
            name='pozicijaOznake',
            field=models.CharField(default='err', max_length=1000),
        ),
        migrations.AddField(
            model_name='pravilnonepravilnomodel',
            name='pozicijaOznake',
            field=models.CharField(default='err', max_length=1000),
        ),
    ]
